# Generated by Django 5.2.14 on 2026-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='obtained_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='similarity_score',
            field=models.FloatField(default=0),
        ),
    ]
