# Generated by Django 5.2.14 on 2026-05-15 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_alter_interviewrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField(default=0)),
                ('obtained_marks', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Malpractice', 'Malpractice'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
